export const THEME_PRESET_STORAGE_KEY = 'whithin-app-theme-preset';

export const THEME_PRESET_IDS = {
  DEFAULT: 'default',
  WHITHIN: 'whithin',
  TWILIGHT: 'twilight',
  AMETHYST: 'amethyst',
  EMBER: 'ember',
  FOREST: 'forest',
  COAL: 'coal',
  MIDNIGHT: 'midnight',
  LIGHT: 'light',
  LIGHT_CREAM: 'light-cream',
  SAKURA: 'sakura',
  OCEAN: 'ocean',
  SUNSET: 'sunset',
  SLATE: 'slate',
  NEON: 'neon',
  WINE: 'wine',
  MINT_DAY: 'mint-day',
  SKY_DAY: 'sky-day',
  COPPER: 'copper',
  BUBBLEGUM: 'bubblegum',
  PAPER: 'paper',
  CYBERPUNK: 'cyberpunk',
  ACID: 'acid',
  NIGHT_CITY: 'night-city',
  AURORA: 'aurora',
  LAGOON: 'lagoon',
  ROYAL: 'royal',
  CANDY_DAY: 'candy-day',
  LAVENDER_DAY: 'lavender-day',
  VOLCANO: 'volcano',
  VAPORWAVE: 'vaporwave',
  BLUEPRINT: 'blueprint',
  TERMINAL_AMBER: 'terminal-amber',
  NOIR: 'noir',
  NEWSPAPER: 'newspaper',
  MATRIX: 'matrix',
  GAMEBOY: 'gameboy',
  COMMODORE_64: 'commodore-64',
  THERMAL: 'thermal',
  CMYK: 'cmyk',
  MAC_PLATINUM: 'mac-platinum',
  DOS_BLUE: 'dos-blue',
  POLAROID: 'polaroid',
  ELECTRIC_STORM: 'electric-storm',
  SUBMARINE: 'submarine',
  SPECTRUM: 'spectrum',
  FLUORESCENT: 'fluorescent',
  RUST: 'rust',
  CANDLELIGHT: 'candlelight',
  INKWELL: 'inkwell',
  MARBLE_DAY: 'marble-day',
  DEEP_SPACE: 'deep-space',
  BIOLUMINESCENCE: 'bioluminescence',
  ARCADE: 'arcade',
  FROSTED_GLASS: 'frosted-glass',
  SYSTEM24: 'system24',
};

/** @type {Record<string, { id: string, name: string, description?: string, colors: Record<string, string> | null }>} */
export const THEME_PRESETS = {
  [THEME_PRESET_IDS.DEFAULT]: {
    id: THEME_PRESET_IDS.DEFAULT,
    name: 'По умолчанию',
    description: 'Классическая тёмная тема в духе Discord',
    colors: null,
  },
  [THEME_PRESET_IDS.WHITHIN]: {
    id: THEME_PRESET_IDS.WHITHIN,
    name: 'Whithin',
    description: 'Фирменная тёмная палитра Whithin с красным акцентом',
    colors: {
      '--background': '#141010',
      '--background-primary': '#080606',
      '--background-secondary': '#1a1212',
      '--surface': '#221616',
      '--surface-hover': '#2e1a1a',
      '--text': '#ffffff',
      '--text-muted': '#9a8585',
      '--text-secondary': '#c9b5b5',
      '--primary': '#e60012',
      '--primary-hover': '#b8000e',
      '--border': '#4a2020',
      '--server-list-background': '#000000',
    },
  },
  [THEME_PRESET_IDS.TWILIGHT]: {
    id: THEME_PRESET_IDS.TWILIGHT,
    name: 'Сумерки',
    description: 'Холодные синие оттенки и бирюзовый акцент — мягче для глаз ночью',
    colors: {
      '--background': '#1a1f2e',
      '--background-primary': '#151925',
      '--background-secondary': '#212738',
      '--surface': '#252b3a',
      '--surface-hover': '#2f3647',
      '--text': '#e8ecf4',
      '--text-muted': '#8b93a7',
      '--text-secondary': '#aab2c4',
      '--primary': '#38bdf8',
      '--primary-hover': '#0ea5e9',
      '--border': '#343b4f',
      '--server-list-background': '#111520',
    },
  },
  [THEME_PRESET_IDS.AMETHYST]: {
    id: THEME_PRESET_IDS.AMETHYST,
    name: 'Аметист',
    description: 'Тёплые фиолетовые тона и лавандовый акцент — уютная атмосфера',
    colors: {
      '--background': '#1f1a24',
      '--background-primary': '#18141f',
      '--background-secondary': '#262030',
      '--surface': '#2d2736',
      '--surface-hover': '#3a3344',
      '--text': '#f3eef8',
      '--text-muted': '#9d93ad',
      '--text-secondary': '#b8afc4',
      '--primary': '#a78bfa',
      '--primary-hover': '#8b5cf6',
      '--border': '#423a4f',
      '--server-list-background': '#141019',
    },
  },
  [THEME_PRESET_IDS.EMBER]: {
    id: THEME_PRESET_IDS.EMBER,
    name: 'Янтарь',
    description: 'Тёплые коричневые оттенки и янтарный акцент — как вечерний свет',
    colors: {
      '--background': '#221e1a',
      '--background-primary': '#1a1714',
      '--background-secondary': '#2a2520',
      '--surface': '#322c26',
      '--surface-hover': '#3d3630',
      '--text': '#f5f0ea',
      '--text-muted': '#a89a8c',
      '--text-secondary': '#c4b8aa',
      '--primary': '#f59e0b',
      '--primary-hover': '#d97706',
      '--border': '#4a4239',
      '--server-list-background': '#141210',
    },
  },
  [THEME_PRESET_IDS.FOREST]: {
    id: THEME_PRESET_IDS.FOREST,
    name: 'Лес',
    description: 'Глубокие зелёные тона и изумрудный акцент — спокойная природная палитра',
    colors: {
      '--background': '#1a211c',
      '--background-primary': '#141a16',
      '--background-secondary': '#212a23',
      '--surface': '#28332b',
      '--surface-hover': '#323f35',
      '--text': '#ecf3ee',
      '--text-muted': '#8a9a8f',
      '--text-secondary': '#a8b8ad',
      '--primary': '#34d399',
      '--primary-hover': '#10b981',
      '--border': '#36443a',
      '--server-list-background': '#101512',
    },
  },
  [THEME_PRESET_IDS.COAL]: {
    id: THEME_PRESET_IDS.COAL,
    name: 'Уголь',
    description: 'Почти чёрная OLED-палитра — максимальный контраст и минимум отвлекающих оттенков',
    colors: {
      '--background': '#0a0a0a',
      '--background-primary': '#050505',
      '--background-secondary': '#111111',
      '--surface': '#171717',
      '--surface-hover': '#212121',
      '--text': '#f5f5f5',
      '--text-muted': '#737373',
      '--text-secondary': '#a3a3a3',
      '--primary': '#a1a1aa',
      '--primary-hover': '#d4d4d4',
      '--border': '#2a2a2a',
      '--server-list-background': '#000000',
    },
  },
  [THEME_PRESET_IDS.MIDNIGHT]: {
    id: THEME_PRESET_IDS.MIDNIGHT,
    name: 'Полночь',
    description: 'Глубокий индиго и мягкий перiwinkle-акцент — спокойная ночная палитра',
    colors: {
      '--background': '#16162a',
      '--background-primary': '#0f0f1a',
      '--background-secondary': '#1c1c32',
      '--surface': '#222240',
      '--surface-hover': '#2c2c50',
      '--text': '#ececf4',
      '--text-muted': '#8b8ba8',
      '--text-secondary': '#b0b0cc',
      '--primary': '#7c89ff',
      '--primary-hover': '#6370e8',
      '--border': '#34345a',
      '--server-list-background': '#0a0a14',
    },
  },
  [THEME_PRESET_IDS.LIGHT]: {
    id: THEME_PRESET_IDS.LIGHT,
    name: 'Светлая',
    description: 'Светлые поверхности и тёмный текст — удобно днём и при ярком освещении',
    colors: {
      '--background': '#ffffff',
      '--background-primary': '#f2f3f5',
      '--background-secondary': '#ebedef',
      '--surface': '#f2f3f5',
      '--surface-hover': '#e3e5e8',
      '--text': '#060607',
      '--text-muted': '#5e626a',
      '--text-secondary': '#46484d',
      '--primary': '#5865f2',
      '--primary-hover': '#4752c4',
      '--border': '#dce0e6',
      '--server-list-background': '#e3e5e8',
      '--icon': '#5e626a',
      '--icon-hover': '#060607',
    },
  },
  [THEME_PRESET_IDS.LIGHT_CREAM]: {
    id: THEME_PRESET_IDS.LIGHT_CREAM,
    name: 'Молочная',
    description: 'Тёплые кремовые тона и мягкий карамельный акцент — уютно и спокойно днём',
    colors: {
      '--background': '#faf8f5',
      '--background-primary': '#f3f0eb',
      '--background-secondary': '#ebe6df',
      '--surface': '#f3f0eb',
      '--surface-hover': '#e8e3db',
      '--text': '#1a1816',
      '--text-muted': '#6b6560',
      '--text-secondary': '#4a4541',
      '--primary': '#9a8268',
      '--primary-hover': '#807055',
      '--border': '#ddd6cc',
      '--server-list-background': '#ebe6df',
      '--icon': '#6b6560',
      '--icon-hover': '#1a1816',
    },
  },
  [THEME_PRESET_IDS.SAKURA]: {
    id: THEME_PRESET_IDS.SAKURA,
    name: 'Сакура',
    description: 'Тёмно-розовые тона и нежный акцент — спокойная весенняя палитра',
    colors: {
      '--background': '#1f181b',
      '--background-primary': '#181216',
      '--background-secondary': '#271e23',
      '--surface': '#2d2329',
      '--surface-hover': '#3a2e36',
      '--text': '#fce7f3',
      '--text-muted': '#a78b9a',
      '--text-secondary': '#d4aeb8',
      '--primary': '#f472b6',
      '--primary-hover': '#ec4899',
      '--border': '#4a3540',
      '--server-list-background': '#141018',
    },
  },
  [THEME_PRESET_IDS.OCEAN]: {
    id: THEME_PRESET_IDS.OCEAN,
    name: 'Океан',
    description: 'Глубокие сине-зелёные оттенки и бирюзовый акцент — как глубина моря',
    colors: {
      '--background': '#0f1a22',
      '--background-primary': '#0a1419',
      '--background-secondary': '#152530',
      '--surface': '#1a2e3a',
      '--surface-hover': '#243a48',
      '--text': '#e0f2fe',
      '--text-muted': '#7da3b8',
      '--text-secondary': '#a8c5d4',
      '--primary': '#22d3ee',
      '--primary-hover': '#06b6d4',
      '--text-on-primary': '#042f2e',
      '--border': '#2a4554',
      '--server-list-background': '#060e12',
    },
  },
  [THEME_PRESET_IDS.SUNSET]: {
    id: THEME_PRESET_IDS.SUNSET,
    name: 'Закат',
    description: 'Тёплые терракотовые тона и оранжевый акцент — мягкий вечерний свет',
    colors: {
      '--background': '#221a18',
      '--background-primary': '#1a1412',
      '--background-secondary': '#2a211e',
      '--surface': '#322825',
      '--surface-hover': '#3f332f',
      '--text': '#fef3e8',
      '--text-muted': '#b09a8c',
      '--text-secondary': '#d4c0b0',
      '--primary': '#fb923c',
      '--primary-hover': '#f97316',
      '--border': '#4a3d36',
      '--server-list-background': '#141010',
    },
  },
  [THEME_PRESET_IDS.SLATE]: {
    id: THEME_PRESET_IDS.SLATE,
    name: 'Графит',
    description: 'Нейтральные серо-синие тона — сдержанная профессиональная палитра',
    colors: {
      '--background': '#1c1f26',
      '--background-primary': '#15171c',
      '--background-secondary': '#252830',
      '--surface': '#2c303a',
      '--surface-hover': '#363b48',
      '--text': '#e8eaed',
      '--text-muted': '#8b919d',
      '--text-secondary': '#aeb4bf',
      '--primary': '#94a3b8',
      '--primary-hover': '#64748b',
      '--border': '#3d4450',
      '--server-list-background': '#121418',
    },
  },
  [THEME_PRESET_IDS.NEON]: {
    id: THEME_PRESET_IDS.NEON,
    name: 'Неон',
    description: 'Чёрный OLED-фон и кислотно-зелёный акцент — контраст в стиле терминала',
    colors: {
      '--background': '#050805',
      '--background-primary': '#020402',
      '--background-secondary': '#0a120a',
      '--surface': '#0f180f',
      '--surface-hover': '#162216',
      '--text': '#eaffea',
      '--text-muted': '#6b8f6b',
      '--text-secondary': '#9fcf9f',
      '--primary': '#39ff14',
      '--primary-hover': '#22c55e',
      '--border': '#1a3a1a',
      '--server-list-background': '#000000',
    },
  },
  [THEME_PRESET_IDS.WINE]: {
    id: THEME_PRESET_IDS.WINE,
    name: 'Вино',
    description: 'Глубокий бордовый фон и золотой акцент — тёплая «камерная» атмосфера',
    colors: {
      '--background': '#1a0b10',
      '--background-primary': '#12070b',
      '--background-secondary': '#241018',
      '--surface': '#2d141c',
      '--surface-hover': '#3a1a25',
      '--text': '#f8ece8',
      '--text-muted': '#a67a82',
      '--text-secondary': '#c9a0a8',
      '--primary': '#d4af37',
      '--primary-hover': '#b8922e',
      '--border': '#4a2430',
      '--server-list-background': '#0d0508',
    },
  },
  [THEME_PRESET_IDS.COPPER]: {
    id: THEME_PRESET_IDS.COPPER,
    name: 'Медь',
    description: 'Тёмный сине-зелёный фон и медно-оранжевый акцент — индustrial-палитра',
    colors: {
      '--background': '#101816',
      '--background-primary': '#0a100e',
      '--background-secondary': '#162220',
      '--surface': '#1c2b28',
      '--surface-hover': '#243632',
      '--text': '#e8f0ed',
      '--text-muted': '#7a948c',
      '--text-secondary': '#a3bdb4',
      '--primary': '#e09540',
      '--primary-hover': '#c47a2a',
      '--border': '#2d4540',
      '--server-list-background': '#060b0a',
    },
  },
  [THEME_PRESET_IDS.BUBBLEGUM]: {
    id: THEME_PRESET_IDS.BUBBLEGUM,
    name: 'Жвачка',
    description: 'Тёмная фуксия и ярко-розовый акцент — смелая pop-палитра, не похожая на «Сакуру»',
    colors: {
      '--background': '#180818',
      '--background-primary': '#100410',
      '--background-secondary': '#240c24',
      '--surface': '#2d1030',
      '--surface-hover': '#3a1540',
      '--text': '#ffe8fb',
      '--text-muted': '#c77ab8',
      '--text-secondary': '#e8a8dc',
      '--primary': '#ff2d95',
      '--primary-hover': '#e6007a',
      '--border': '#4a2050',
      '--server-list-background': '#0c040c',
    },
  },
  [THEME_PRESET_IDS.MINT_DAY]: {
    id: THEME_PRESET_IDS.MINT_DAY,
    name: 'Мята',
    description: 'Светлая мятная палитра с изумрудным акцентом — свежо и спокойно днём',
    colors: {
      '--background': '#f0fdf7',
      '--background-primary': '#e6faf1',
      '--background-secondary': '#dcf5ea',
      '--surface': '#e6faf1',
      '--surface-hover': '#d4f0e3',
      '--text': '#0f2e24',
      '--text-muted': '#4d7366',
      '--text-secondary': '#2f5548',
      '--primary': '#059669',
      '--primary-hover': '#047857',
      '--border': '#b8e6d0',
      '--server-list-background': '#dcf5ea',
      '--icon': '#4d7366',
      '--icon-hover': '#0f2e24',
    },
  },
  [THEME_PRESET_IDS.SKY_DAY]: {
    id: THEME_PRESET_IDS.SKY_DAY,
    name: 'Небо',
    description: 'Светло-голубая палитра с насыщенным синим акцентом — ясный дневной интерфейс',
    colors: {
      '--background': '#f0f7ff',
      '--background-primary': '#e3effc',
      '--background-secondary': '#d6e8fa',
      '--surface': '#e3effc',
      '--surface-hover': '#cfe0f5',
      '--text': '#0c1a33',
      '--text-muted': '#4a6280',
      '--text-secondary': '#2f4563',
      '--primary': '#2563eb',
      '--primary-hover': '#1d4ed8',
      '--border': '#c5d9f2',
      '--server-list-background': '#d6e8fa',
      '--icon': '#4a6280',
      '--icon-hover': '#0c1a33',
    },
  },
  [THEME_PRESET_IDS.PAPER]: {
    id: THEME_PRESET_IDS.PAPER,
    name: 'Бумага',
    description: 'Тёплый светлый фон с терракотовым акцентом — как блокнот, не похож на «Молочную»',
    colors: {
      '--background': '#faf6f0',
      '--background-primary': '#f3ede4',
      '--background-secondary': '#ebe3d6',
      '--surface': '#f3ede4',
      '--surface-hover': '#e6ddd0',
      '--text': '#2a2218',
      '--text-muted': '#7a6e5e',
      '--text-secondary': '#544a3c',
      '--primary': '#c45c26',
      '--primary-hover': '#a34a1c',
      '--border': '#d9cfc0',
      '--server-list-background': '#ebe3d6',
      '--icon': '#7a6e5e',
      '--icon-hover': '#2a2218',
    },
  },
  [THEME_PRESET_IDS.CYBERPUNK]: {
    id: THEME_PRESET_IDS.CYBERPUNK,
    name: 'Киберпанк',
    description: 'Стиль Cyberpunk 2077: красный интерфейс, cyan — входящие, жёлтый — исходящие',
    colors: {
      '--background': '#0c0808',
      '--background-primary': '#080606',
      '--background-secondary': '#120c0c',
      '--surface': '#161010',
      '--surface-hover': '#201818',
      '--text': '#fcee09',
      '--text-muted': '#c9ba00',
      '--text-secondary': '#e8d908',
      '--primary': '#00f0f0',
      '--primary-hover': '#00c4d4',
      '--border': '#5c1820',
      '--server-list-background': '#060404',
      '--icon': '#fcee09',
      '--icon-hover': '#fff176',
      '--text-on-primary': '#0a0a0a',
    },
  },
  [THEME_PRESET_IDS.ACID]: {
    id: THEME_PRESET_IDS.ACID,
    name: 'Кислота',
    description: 'Кислотно-зелёный акцент на глубоком фиолетовом фоне — контраст комплементарных цветов',
    colors: {
      '--background': '#140a1c',
      '--background-primary': '#0c0612',
      '--background-secondary': '#1c1028',
      '--surface': '#241432',
      '--surface-hover': '#301a42',
      '--text': '#f0ffe8',
      '--text-muted': '#a890c0',
      '--text-secondary': '#c8b8e0',
      '--primary': '#ccff00',
      '--primary-hover': '#a8d900',
      '--border': '#5a2080',
      '--server-list-background': '#080410',
    },
  },
  [THEME_PRESET_IDS.NIGHT_CITY]: {
    id: THEME_PRESET_IDS.NIGHT_CITY,
    name: 'Night City',
    description: 'Неоновый cyan и жёлтые акценты на глубоком чёрном — атмосфера ночного мегаполиса',
    colors: {
      '--background': '#101010',
      '--background-primary': '#0a0a0a',
      '--background-secondary': '#161616',
      '--surface': '#1a1a1a',
      '--surface-hover': '#242424',
      '--text': '#4ee2c0',
      '--text-muted': '#4ee2c0',
      '--text-secondary': '#4ee2c0',
      '--primary': '#fcee09',
      '--primary-hover': '#d4c908',
      '--border': '#3a3820',
      '--server-list-background': '#060606',
      '--text-on-primary': '#0a0a0a',
    },
  },
  [THEME_PRESET_IDS.AURORA]: {
    id: THEME_PRESET_IDS.AURORA,
    name: 'Аврора',
    description: 'Северное сияние: глубокий арктический фон, зелёно-фиолетовые акценты и мягкий холодный текст',
    colors: {
      '--background': '#07121f',
      '--background-primary': '#050c16',
      '--background-secondary': '#0d1a2b',
      '--surface': '#13253a',
      '--surface-hover': '#1b314b',
      '--text': '#eaf7ff',
      '--text-muted': '#7ea4b8',
      '--text-secondary': '#afd4e5',
      '--primary': '#66f2b8',
      '--primary-hover': '#35d49a',
      '--text-on-primary': '#07121f',
      '--border': '#24445c',
      '--server-list-background': '#030812',
    },
  },
  [THEME_PRESET_IDS.LAGOON]: {
    id: THEME_PRESET_IDS.LAGOON,
    name: 'Лагуна',
    description: 'Тёплая морская палитра: тёмная бирюза, песочный акцент и спокойные голубые поверхности',
    colors: {
      '--background': '#0b1f24',
      '--background-primary': '#061519',
      '--background-secondary': '#102b31',
      '--surface': '#173840',
      '--surface-hover': '#214a54',
      '--text': '#ecfbf7',
      '--text-muted': '#82aaa4',
      '--text-secondary': '#afd2ca',
      '--primary': '#f4c76b',
      '--primary-hover': '#e0a93a',
      '--border': '#2d5a62',
      '--server-list-background': '#041014',
      '--text-on-primary': '#1f1605',
    },
  },
  [THEME_PRESET_IDS.ROYAL]: {
    id: THEME_PRESET_IDS.ROYAL,
    name: 'Королевская',
    description: 'Глубокий фиолетово-синий фон с золотым акцентом — контрастная и торжественная тема',
    colors: {
      '--background': '#151128',
      '--background-primary': '#0e0a1d',
      '--background-secondary': '#1d1835',
      '--surface': '#282044',
      '--surface-hover': '#342a58',
      '--text': '#f4efff',
      '--text-muted': '#9d91bc',
      '--text-secondary': '#c7bce2',
      '--primary': '#ffd166',
      '--primary-hover': '#f4b942',
      '--border': '#46386a',
      '--server-list-background': '#090614',
      '--text-on-primary': '#211400',
    },
  },
  [THEME_PRESET_IDS.CANDY_DAY]: {
    id: THEME_PRESET_IDS.CANDY_DAY,
    name: 'Конфета',
    description: 'Светлая playful-тема: молочно-розовые поверхности, ягодный акцент и мягкий фиолетовый текст',
    colors: {
      '--background': '#fff7fb',
      '--background-primary': '#fff0f7',
      '--background-secondary': '#fbe7f1',
      '--surface': '#fff0f7',
      '--surface-hover': '#f5d9e8',
      '--text': '#2d1525',
      '--text-muted': '#875672',
      '--text-secondary': '#5f2d4d',
      '--primary': '#d946ef',
      '--primary-hover': '#c026d3',
      '--border': '#efc9dd',
      '--server-list-background': '#fbe7f1',
      '--icon': '#875672',
      '--icon-hover': '#2d1525',
    },
  },
  [THEME_PRESET_IDS.LAVENDER_DAY]: {
    id: THEME_PRESET_IDS.LAVENDER_DAY,
    name: 'Лаванда',
    description: 'Светлая лавандовая тема: мягкий фиолетовый фон и насыщенный пурпурный акцент',
    colors: {
      '--background': '#faf8ff',
      '--background-primary': '#f3effc',
      '--background-secondary': '#ebe4f8',
      '--surface': '#f5f0fd',
      '--surface-hover': '#e8dff5',
      '--text': '#2a1f3d',
      '--text-muted': '#7a6b96',
      '--text-secondary': '#4a3d66',
      '--primary': '#7c4dff',
      '--primary-hover': '#651fff',
      '--border': '#d8ccef',
      '--server-list-background': '#ebe4f8',
      '--icon': '#7a6b96',
      '--icon-hover': '#2a1f3d',
    },
  },
  [THEME_PRESET_IDS.VOLCANO]: {
    id: THEME_PRESET_IDS.VOLCANO,
    name: 'Вулкан',
    description: 'Огненная тёмная тема: вулканический фон, лавовый оранжевый акцент и тёплый пепельный текст',
    colors: {
      '--background': '#1a0a0a',
      '--background-primary': '#120606',
      '--background-secondary': '#261010',
      '--surface': '#321818',
      '--surface-hover': '#421e1e',
      '--text': '#ffe8e0',
      '--text-muted': '#a06858',
      '--text-secondary': '#d4907a',
      '--primary': '#ff5722',
      '--primary-hover': '#e64a19',
      '--border': '#5c2820',
      '--server-list-background': '#0a0404',
      '--text-on-primary': '#1a0a0a',
    },
  },
  [THEME_PRESET_IDS.MATRIX]: {
    id: THEME_PRESET_IDS.MATRIX,
    name: 'Матрица',
    description: 'Терминальная зелёная тема в духе «Матрицы»: чёрный фон и неоновый зелёный акцент',
    colors: {
      '--background': '#0a0f0a',
      '--background-primary': '#050805',
      '--background-secondary': '#0d140d',
      '--surface': '#121a12',
      '--surface-hover': '#1a241a',
      '--text': '#c8e6c8',
      '--text-muted': '#3a6a3a',
      '--text-secondary': '#5aff5a',
      '--primary': '#00ff41',
      '--primary-hover': '#00cc33',
      '--border': '#1a3a1a',
      '--server-list-background': '#030503',
      '--text-on-primary': '#0a0f0a',
    },
  },
  [THEME_PRESET_IDS.VAPORWAVE]: {
    id: THEME_PRESET_IDS.VAPORWAVE,
    name: 'Вейпорвейв',
    description: 'Эстетика 80-х: глубокий фиолетовый фон, cyan-текст и неоново-розовый акцент',
    colors: {
      '--background': '#1a0533',
      '--background-primary': '#0f0220',
      '--background-secondary': '#24084a',
      '--surface': '#2a1050',
      '--surface-hover': '#381868',
      '--text': '#01cdfe',
      '--text-muted': '#b967ff',
      '--text-secondary': '#ff71ce',
      '--primary': '#ff71ce',
      '--primary-hover': '#ff4db8',
      '--border': '#6b2d9e',
      '--server-list-background': '#0a0118',
      '--text-on-primary': '#1a0533',
    },
  },
  [THEME_PRESET_IDS.BLUEPRINT]: {
    id: THEME_PRESET_IDS.BLUEPRINT,
    name: 'Чертёж',
    description: 'Инженерный чертёж: тёмно-синий фон, бело-голубой текст и cyan-линии',
    colors: {
      '--background': '#0a1628',
      '--background-primary': '#061018',
      '--background-secondary': '#0f2847',
      '--surface': '#143660',
      '--surface-hover': '#1a4480',
      '--text': '#e8f4ff',
      '--text-muted': '#5a8ab0',
      '--text-secondary': '#7ec8ff',
      '--primary': '#4db8ff',
      '--primary-hover': '#2aa0f0',
      '--border': '#2a5080',
      '--server-list-background': '#040c14',
      '--text-on-primary': '#0a1628',
    },
  },
  [THEME_PRESET_IDS.TERMINAL_AMBER]: {
    id: THEME_PRESET_IDS.TERMINAL_AMBER,
    name: 'Янтарный CRT',
    description: 'Старый монитор: чистый чёрный фон и монохромный янтарный текст — как DOS-терминал',
    colors: {
      '--background': '#0a0800',
      '--background-primary': '#050400',
      '--background-secondary': '#121000',
      '--surface': '#1a1600',
      '--surface-hover': '#241e00',
      '--text': '#ffb000',
      '--text-muted': '#996600',
      '--text-secondary': '#ffcc44',
      '--primary': '#ffcc00',
      '--primary-hover': '#e6b800',
      '--border': '#4a3800',
      '--server-list-background': '#030200',
      '--text-on-primary': '#0a0800',
      '--icon': '#ffb000',
      '--icon-hover': '#ffcc44',
    },
  },
  [THEME_PRESET_IDS.NOIR]: {
    id: THEME_PRESET_IDS.NOIR,
    name: 'Нуар',
    description: 'Чёрно-белое кино: монохромная палитра без цвета — только серебристый акцент',
    colors: {
      '--background': '#0a0a0a',
      '--background-primary': '#050505',
      '--background-secondary': '#121212',
      '--surface': '#1a1a1a',
      '--surface-hover': '#242424',
      '--text': '#f0f0f0',
      '--text-muted': '#888888',
      '--text-secondary': '#c0c0c0',
      '--primary': '#d4d4d4',
      '--primary-hover': '#ffffff',
      '--border': '#333333',
      '--server-list-background': '#000000',
      '--text-on-primary': '#0a0a0a',
      '--icon': '#aaaaaa',
      '--icon-hover': '#f0f0f0',
    },
  },
  [THEME_PRESET_IDS.NEWSPAPER]: {
    id: THEME_PRESET_IDS.NEWSPAPER,
    name: 'Газета',
    description: 'Газетная вёрстка: кремовая бумага, чёрные чернила и красные заголовки',
    colors: {
      '--background': '#f4f1ea',
      '--background-primary': '#ebe6db',
      '--background-secondary': '#e0dace',
      '--surface': '#ebe6db',
      '--surface-hover': '#ddd6c8',
      '--text': '#1a1a1a',
      '--text-muted': '#5a5a5a',
      '--text-secondary': '#333333',
      '--primary': '#8b0000',
      '--primary-hover': '#6b0000',
      '--border': '#c8c0b0',
      '--server-list-background': '#e0dace',
      '--icon': '#5a5a5a',
      '--icon-hover': '#1a1a1a',
    },
  },
  [THEME_PRESET_IDS.GAMEBOY]: {
    id: THEME_PRESET_IDS.GAMEBOY,
    name: 'Game Boy',
    description: 'Монохромный LCD Game Boy: четыре оттенка зелёного, как на экране портативки',
    colors: {
      '--background': '#0f380f',
      '--background-primary': '#0a280a',
      '--background-secondary': '#306230',
      '--surface': '#306230',
      '--surface-hover': '#8bac0f',
      '--text': '#9bbc0f',
      '--text-muted': '#8bac0f',
      '--text-secondary': '#9bbc0f',
      '--primary': '#9bbc0f',
      '--primary-hover': '#8bac0f',
      '--border': '#306230',
      '--server-list-background': '#0a280a',
      '--text-on-primary': '#0f380f',
    },
  },
  [THEME_PRESET_IDS.COMMODORE_64]: {
    id: THEME_PRESET_IDS.COMMODORE_64,
    name: 'Commodore 64',
    description: 'Синий экран C64: фирменный синий фон и зелёные акценты кнопок',
    colors: {
      '--background': '#40318d',
      '--background-primary': '#302070',
      '--background-secondary': '#5040a0',
      '--surface': '#5040a0',
      '--surface-hover': '#7869c4',
      '--text': '#b8b8ff',
      '--text-muted': '#7869c4',
      '--text-secondary': '#9ad284',
      '--primary': '#9ad284',
      '--primary-hover': '#7ab864',
      '--border': '#7869c4',
      '--server-list-background': '#302070',
      '--text-on-primary': '#40318d',
    },
  },
  [THEME_PRESET_IDS.THERMAL]: {
    id: THEME_PRESET_IDS.THERMAL,
    name: 'Тепловизор',
    description: 'Тепловая камера: чёрный фон, холодный синий текст и горячий красный акцент',
    colors: {
      '--background': '#0a0a0a',
      '--background-primary': '#050505',
      '--background-secondary': '#141010',
      '--surface': '#1a1010',
      '--surface-hover': '#281818',
      '--text': '#c0c0ff',
      '--text-muted': '#6060a0',
      '--text-secondary': '#ff9900',
      '--primary': '#ff2200',
      '--primary-hover': '#e01000',
      '--border': '#301818',
      '--server-list-background': '#020202',
      '--text-on-primary': '#0a0a0a',
    },
  },
  [THEME_PRESET_IDS.CMYK]: {
    id: THEME_PRESET_IDS.CMYK,
    name: 'CMYK',
    description: 'Полиграфия: белая бумага, чёрный текст и акценты cyan и magenta',
    colors: {
      '--background': '#f5f2eb',
      '--background-primary': '#ebe8e0',
      '--background-secondary': '#e0ddd5',
      '--surface': '#ebe8e0',
      '--surface-hover': '#d8d5cd',
      '--text': '#1a1a1a',
      '--text-muted': '#505050',
      '--text-secondary': '#ec008c',
      '--primary': '#00aeef',
      '--primary-hover': '#0090cc',
      '--border': '#c8c8c0',
      '--server-list-background': '#e0ddd5',
      '--icon': '#505050',
      '--icon-hover': '#1a1a1a',
    },
  },
  [THEME_PRESET_IDS.MAC_PLATINUM]: {
    id: THEME_PRESET_IDS.MAC_PLATINUM,
    name: 'Mac Platinum',
    description: 'Классический Mac OS 9: платиновый серый интерфейс и чёрные акценты',
    colors: {
      '--background': '#dddddd',
      '--background-primary': '#cccccc',
      '--background-secondary': '#eeeeee',
      '--surface': '#eeeeee',
      '--surface-hover': '#f5f5f5',
      '--text': '#000000',
      '--text-muted': '#666666',
      '--text-secondary': '#333333',
      '--primary': '#000000',
      '--primary-hover': '#333333',
      '--border': '#999999',
      '--server-list-background': '#cccccc',
      '--icon': '#333333',
      '--icon-hover': '#000000',
      '--text-on-primary': '#ffffff',
    },
  },
  [THEME_PRESET_IDS.DOS_BLUE]: {
    id: THEME_PRESET_IDS.DOS_BLUE,
    name: 'MS-DOS',
    description: 'Синий экран DOS: серый текст на насыщенном синем фоне',
    colors: {
      '--background': '#0000aa',
      '--background-primary': '#000088',
      '--background-secondary': '#0000cc',
      '--surface': '#0000cc',
      '--surface-hover': '#2222dd',
      '--text': '#aaaaaa',
      '--text-muted': '#5555ff',
      '--text-secondary': '#ffffff',
      '--primary': '#ffffff',
      '--primary-hover': '#dddddd',
      '--border': '#0000ff',
      '--server-list-background': '#000088',
      '--text-on-primary': '#0000aa',
    },
  },
  [THEME_PRESET_IDS.POLAROID]: {
    id: THEME_PRESET_IDS.POLAROID,
    name: 'Полароид',
    description: 'Выцветшая фотография: тёплый кремовый тон и приглушённые коричневые оттенки',
    colors: {
      '--background': '#f2e8d5',
      '--background-primary': '#e8dcc8',
      '--background-secondary': '#ddd0bc',
      '--surface': '#e8dcc8',
      '--surface-hover': '#d4c4b0',
      '--text': '#4a3c30',
      '--text-muted': '#8a7a68',
      '--text-secondary': '#6a5a48',
      '--primary': '#c4785a',
      '--primary-hover': '#a86048',
      '--border': '#c8b8a4',
      '--server-list-background': '#ddd0bc',
      '--icon': '#8a7a68',
      '--icon-hover': '#4a3c30',
    },
  },
  [THEME_PRESET_IDS.ELECTRIC_STORM]: {
    id: THEME_PRESET_IDS.ELECTRIC_STORM,
    name: 'Гроза',
    description: 'Грозовое небо: тёмно-синий фон, фиолетовые вспышки молний и холодный текст',
    colors: {
      '--background': '#0c0c18',
      '--background-primary': '#060610',
      '--background-secondary': '#141428',
      '--surface': '#181828',
      '--surface-hover': '#222238',
      '--text': '#c8c8e8',
      '--text-muted': '#606080',
      '--text-secondary': '#e0e0ff',
      '--primary': '#a855f7',
      '--primary-hover': '#9030e0',
      '--border': '#2a2a48',
      '--server-list-background': '#040408',
      '--text-on-primary': '#0c0c18',
    },
  },
  [THEME_PRESET_IDS.SUBMARINE]: {
    id: THEME_PRESET_IDS.SUBMARINE,
    name: 'Подлодка',
    description: 'Интерьер подводной лодки: металлический серо-зелёный и тусклые приборные огни',
    colors: {
      '--background': '#1a2428',
      '--background-primary': '#10181c',
      '--background-secondary': '#243038',
      '--surface': '#243038',
      '--surface-hover': '#2e3c44',
      '--text': '#a8b8c0',
      '--text-muted': '#5a6870',
      '--text-secondary': '#6a9aaa',
      '--primary': '#4a8a6a',
      '--primary-hover': '#3a7058',
      '--border': '#3a4850',
      '--server-list-background': '#0c1014',
      '--text-on-primary': '#1a2428',
    },
  },
  [THEME_PRESET_IDS.SPECTRUM]: {
    id: THEME_PRESET_IDS.SPECTRUM,
    name: 'ZX Spectrum',
    description: 'ZX Spectrum: чёрный фон, яркий cyan-текст и красный акцент',
    colors: {
      '--background': '#000000',
      '--background-primary': '#000000',
      '--background-secondary': '#1a1a1a',
      '--surface': '#1a1a1a',
      '--surface-hover': '#2a2a2a',
      '--text': '#00ffff',
      '--text-muted': '#008888',
      '--text-secondary': '#ffff00',
      '--primary': '#ff0000',
      '--primary-hover': '#dd0000',
      '--border': '#333333',
      '--server-list-background': '#000000',
      '--text-on-primary': '#000000',
    },
  },
  [THEME_PRESET_IDS.FLUORESCENT]: {
    id: THEME_PRESET_IDS.FLUORESCENT,
    name: 'Ультрафиолет',
    description: 'Blacklight: глубокий UV-фиолетовый фон и флуоресцентный розовый текст',
    colors: {
      '--background': '#1a0028',
      '--background-primary': '#100018',
      '--background-secondary': '#280040',
      '--surface': '#280040',
      '--surface-hover': '#380058',
      '--text': '#ff2bd6',
      '--text-muted': '#a040c0',
      '--text-secondary': '#adff2f',
      '--primary': '#adff2f',
      '--primary-hover': '#90dd20',
      '--border': '#500070',
      '--server-list-background': '#0a0010',
      '--text-on-primary': '#1a0028',
    },
  },
  [THEME_PRESET_IDS.RUST]: {
    id: THEME_PRESET_IDS.RUST,
    name: 'Ржавчина',
    description: 'Индустриальный стиль: стальной серый фон и ржаво-оранжевый акцент',
    colors: {
      '--background': '#2a2a2e',
      '--background-primary': '#1e1e22',
      '--background-secondary': '#36363c',
      '--surface': '#36363c',
      '--surface-hover': '#44444c',
      '--text': '#d0d0d4',
      '--text-muted': '#888890',
      '--text-secondary': '#a0a0a8',
      '--primary': '#b7410e',
      '--primary-hover': '#9a380c',
      '--border': '#505058',
      '--server-list-background': '#1a1a1e',
      '--text-on-primary': '#ffffff',
    },
  },
  [THEME_PRESET_IDS.CANDLELIGHT]: {
    id: THEME_PRESET_IDS.CANDLELIGHT,
    name: 'Свеча',
    description: 'Тёмная комната при свече: тёплый янтарный свет на глубоком коричневом фоне',
    colors: {
      '--background': '#1a1408',
      '--background-primary': '#100c04',
      '--background-secondary': '#241c10',
      '--surface': '#241c10',
      '--surface-hover': '#302818',
      '--text': '#f5e6c8',
      '--text-muted': '#a08860',
      '--text-secondary': '#e8c878',
      '--primary': '#e8b84a',
      '--primary-hover': '#d0a030',
      '--border': '#3a3020',
      '--server-list-background': '#0c0804',
      '--text-on-primary': '#1a1408',
    },
  },
  [THEME_PRESET_IDS.INKWELL]: {
    id: THEME_PRESET_IDS.INKWELL,
    name: 'Чернильница',
    description: 'Глубокий тёмно-синий фон с золотыми чернильными акцентами',
    colors: {
      '--background': '#0a1628',
      '--background-primary': '#060e1a',
      '--background-secondary': '#102040',
      '--surface': '#102040',
      '--surface-hover': '#1a2c58',
      '--text': '#e8dcc0',
      '--text-muted': '#8090a8',
      '--text-secondary': '#c9a227',
      '--primary': '#c9a227',
      '--primary-hover': '#b08c20',
      '--border': '#2a3860',
      '--server-list-background': '#040810',
      '--text-on-primary': '#0a1628',
    },
  },
  [THEME_PRESET_IDS.MARBLE_DAY]: {
    id: THEME_PRESET_IDS.MARBLE_DAY,
    name: 'Мрамор',
    description: 'Светлый мрамор: бело-серые прожилки и графитовый текст',
    colors: {
      '--background': '#f0eeec',
      '--background-primary': '#e8e6e4',
      '--background-secondary': '#dcdad8',
      '--surface': '#e8e6e4',
      '--surface-hover': '#d0cecc',
      '--text': '#2a2a2e',
      '--text-muted': '#6a6a70',
      '--text-secondary': '#4a4a50',
      '--primary': '#4a4a50',
      '--primary-hover': '#3a3a40',
      '--border': '#c8c6c4',
      '--server-list-background': '#dcdad8',
      '--icon': '#6a6a70',
      '--icon-hover': '#2a2a2e',
    },
  },
  [THEME_PRESET_IDS.DEEP_SPACE]: {
    id: THEME_PRESET_IDS.DEEP_SPACE,
    name: 'Космос',
    description: 'Глубокий космос: чёрная пустота, золотые звёзды и фиолетовая туманность',
    colors: {
      '--background': '#040408',
      '--background-primary': '#020204',
      '--background-secondary': '#0a0a14',
      '--surface': '#0a0a14',
      '--surface-hover': '#121220',
      '--text': '#e8e0f0',
      '--text-muted': '#6860a0',
      '--text-secondary': '#ffd700',
      '--primary': '#9b59b6',
      '--primary-hover': '#8040a0',
      '--border': '#201830',
      '--server-list-background': '#010102',
      '--text-on-primary': '#040408',
    },
  },
  [THEME_PRESET_IDS.BIOLUMINESCENCE]: {
    id: THEME_PRESET_IDS.BIOLUMINESCENCE,
    name: 'Биолюминесценция',
    description: 'Глубоководное свечение: тёмная бездна и яркий бирюзовый свет медуз',
    colors: {
      '--background': '#020810',
      '--background-primary': '#010408',
      '--background-secondary': '#041018',
      '--surface': '#041018',
      '--surface-hover': '#081828',
      '--text': '#80ffe8',
      '--text-muted': '#308878',
      '--text-secondary': '#40ffd0',
      '--primary': '#00ffcc',
      '--primary-hover': '#00ddb0',
      '--border': '#0a2838',
      '--server-list-background': '#000408',
      '--text-on-primary': '#020810',
    },
  },
  [THEME_PRESET_IDS.ARCADE]: {
    id: THEME_PRESET_IDS.ARCADE,
    name: 'Аркада',
    description: 'Игровой автомат 80-х: чёрный корпус, магента и электрический жёлтый',
    colors: {
      '--background': '#0a0a0a',
      '--background-primary': '#050505',
      '--background-secondary': '#141414',
      '--surface': '#141414',
      '--surface-hover': '#1e1e1e',
      '--text': '#ffff00',
      '--text-muted': '#a0a000',
      '--text-secondary': '#00ffff',
      '--primary': '#ff00ff',
      '--primary-hover': '#dd00dd',
      '--border': '#333333',
      '--server-list-background': '#020202',
      '--text-on-primary': '#0a0a0a',
    },
  },
  [THEME_PRESET_IDS.FROSTED_GLASS]: {
    id: THEME_PRESET_IDS.FROSTED_GLASS,
    name: 'Frosted Glass',
    description: 'Тёмная полупрозрачная палитра для пользовательского фона с эффектом матового стекла',
    colors: {
      '--background': '#1a1b1f',
      '--background-primary': '#141519',
      '--background-secondary': '#202229',
      '--surface': '#1c1d22',
      '--surface-hover': '#2a2b32',
      '--text': '#eceef4',
      '--text-muted': '#8b909b',
      '--text-secondary': '#b4b8c4',
      '--primary': '#7c89ff',
      '--primary-hover': '#6370e8',
      '--border': '#3a3d48',
      '--server-list-background': '#101114',
      '--icon': '#b4b8c4',
      '--icon-hover': '#eceef4',
    },
  },
  [THEME_PRESET_IDS.SYSTEM24]: {
    id: THEME_PRESET_IDS.SYSTEM24,
    name: 'System24',
    description: 'Палитра в духе system24: графитовый фон и фиолетовый акцент',
    colors: {
      '--background': '#303030',
      '--background-primary': '#2b2b2b',
      '--background-secondary': '#353535',
      '--surface': '#333333',
      '--surface-hover': '#3d3d3d',
      '--text': '#f2f2f2',
      '--text-muted': '#8a8a8a',
      '--text-secondary': '#bfbfbf',
      '--primary': '#b084ff',
      '--primary-hover': '#9865f0',
      '--border': 'rgba(255, 255, 255, 0.14)',
      '--server-list-background': '#262626',
      '--icon': '#bfbfbf',
      '--icon-hover': '#f2f2f2',
      '--text-on-primary': '#141414',
    },
  },
};

export const THEME_PRESET_LIST = Object.values(THEME_PRESETS);

const LIGHT_THEME_PRESET_IDS = new Set([
  THEME_PRESET_IDS.LIGHT,
  THEME_PRESET_IDS.LIGHT_CREAM,
  THEME_PRESET_IDS.MINT_DAY,
  THEME_PRESET_IDS.SKY_DAY,
  THEME_PRESET_IDS.PAPER,
  THEME_PRESET_IDS.CANDY_DAY,
  THEME_PRESET_IDS.LAVENDER_DAY,
  THEME_PRESET_IDS.NEWSPAPER,
  THEME_PRESET_IDS.CMYK,
  THEME_PRESET_IDS.MAC_PLATINUM,
  THEME_PRESET_IDS.POLAROID,
  THEME_PRESET_IDS.MARBLE_DAY,
]);

export function isLightThemePreset(presetId) {
  return LIGHT_THEME_PRESET_IDS.has(presetId);
}


const REMOVED_THEME_MIGRATIONS = {
  'solarized-dark': 'ocean',
  dracula: 'amethyst',
  monokai: 'coal',
  mocha: 'ember',
  matcha: 'forest',
  'arctic-day': 'sky-day',
  synthwave: 'vaporwave',
  gruvbox: 'ember',
  'tokyo-night': 'midnight',
  everforest: 'forest',
  'rose-pine': 'amethyst',
  catppuccin: 'amethyst',
  'peach-day': 'paper',
  'honey-day': 'light-cream',
  obsidian: 'coal',
  'coral-reef': 'ocean',
  'one-dark': 'slate',
  nord: 'slate',
  'solarized-light': 'paper',
  jade: 'forest',
  plum: 'amethyst',
  'blood-moon': 'wine',
  'blueberry-day': 'lavender-day',
  sandstorm: 'ember',
  espresso: 'ember',
  radioactive: 'acid',
  'lava-lamp': 'amethyst',
  hologram: 'cyberpunk',
  steampunk: 'copper',
  'windows-95': 'mac-platinum',
  chalkboard: 'forest',
  amiga: 'default',
};

export function getThemePresetId() {
  try {
    const saved = localStorage.getItem(THEME_PRESET_STORAGE_KEY);
    if (saved === 'persona5') {
      localStorage.setItem(THEME_PRESET_STORAGE_KEY, THEME_PRESET_IDS.MIDNIGHT);
      return THEME_PRESET_IDS.MIDNIGHT;
    }
    if (saved === 'whithin-scarlet') {
      localStorage.setItem(THEME_PRESET_STORAGE_KEY, THEME_PRESET_IDS.WHITHIN);
      return THEME_PRESET_IDS.WHITHIN;
    }
    if (saved === 'whithin') {
      try {
        const themeRaw = localStorage.getItem('whithin-app-theme');
        const theme = themeRaw ? JSON.parse(themeRaw) : null;
        if (theme?.['--primary'] === '#5865f2' && theme?.['--background'] === '#1e1f22') {
          localStorage.setItem(THEME_PRESET_STORAGE_KEY, THEME_PRESET_IDS.DEFAULT);
          return THEME_PRESET_IDS.DEFAULT;
        }
      } catch {
        /* ignore */
      }
    }
    if (saved && REMOVED_THEME_MIGRATIONS[saved]) {
      const migrated = REMOVED_THEME_MIGRATIONS[saved];
      localStorage.setItem(THEME_PRESET_STORAGE_KEY, migrated);
      return migrated;
    }
    if (saved && THEME_PRESETS[saved]) return saved;
  } catch {
    /* ignore */
  }
  return THEME_PRESET_IDS.DEFAULT;
}

export function getBaseThemeForPreset(presetId, defaultTheme) {
  const preset = THEME_PRESETS[presetId] || THEME_PRESETS[THEME_PRESET_IDS.DEFAULT];
  if (!preset.colors) return { ...defaultTheme };
  return { ...defaultTheme, ...preset.colors };
}

export function applyThemePresetAttribute(presetId = getThemePresetId()) {
  const root = document.documentElement;
  if (presetId && presetId !== THEME_PRESET_IDS.DEFAULT) {
    root.setAttribute('data-theme-preset', presetId);
  } else {
    root.removeAttribute('data-theme-preset');
  }
  if (isLightThemePreset(presetId)) {
    root.setAttribute('data-theme-mode', 'light');
  } else {
    root.removeAttribute('data-theme-mode');
  }
}
