name: Deploy to Ubuntu Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: WhithinMessenger.Client/package-lock.json
          
    - name: Install client dependencies
      run: |
        cd WhithinMessenger.Client
        npm ci
        
    - name: Build client
      run: |
        cd WhithinMessenger.Client
        npm run build
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Build backend
      run: |
        dotnet restore WhithinMessenger.Backend/WhithinMessenger.sln
        dotnet build WhithinMessenger.Backend/WhithinMessenger.sln --configuration Release --no-restore
        
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 2.59.41.26
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home
          
          # Останавливаем контейнеры в deploy папке
          echo "Stopping containers..."
          if [ -d "whithin-messenger" ]; then
            cd whithin-messenger
            docker-compose down || true
            docker rm -f whithin-messenger-db-1 whithin-messenger-backend-1 whithin-messenger-client-1 whithin-messenger-nginx-1 2>/dev/null || true
            cd ..
          fi
          
          # Создаем бэкап deploy папки
          echo "Creating backup..."
          if [ -d "whithin-messenger" ]; then
            rm -rf whithin-messenger-backup.old
            mv whithin-messenger-backup whithin-messenger-backup.old 2>/dev/null || true
            cp -r whithin-messenger whithin-messenger-backup || true
          fi
          
          # Очищаем старые образы
          echo "Cleaning old images..."
          docker system prune -f
          
    - name: Upload files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 2.59.41.26
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."
        target: "/home/whithin-messenger"
        strip_components: 0
        
    - name: Start services
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 2.59.41.26
        username: root
        key: ${{ secrets.SERVER_SSH_KEY }}
        timeout: 30m
        script: |
          cd /home/whithin-messenger
          
          # Создаем директории для данных
          echo "Creating data directories..."
          mkdir -p /home/whithin-messenger/data/postgres
          mkdir -p /home/whithin-messenger/data/uploads
          chmod -R 755 /home/whithin-messenger/data
          
          # Устанавливаем права
          echo "Setting permissions..."
          chmod +x docker-compose.yml
          chmod -R 755 /home/whithin-messenger
          
          # Запускаем Docker контейнеры
          echo "Starting services..."
          docker-compose up -d --build
          
          # Ждем запуска базы данных
          echo "Waiting for database to start..."
          sleep 10
          
          # Инициализируем базу данных, если нужно
          echo "Initializing database..."
          docker-compose exec -T db psql -U postgres -d whithin_db -c "SELECT 1;" 2>/dev/null || {
            echo "Database not found, creating..."
            docker-compose exec -T db createdb -U postgres whithin_db 2>/dev/null || true
          }
          
          # Ждем запуска сервисов
          echo "Waiting for services to start..."
          sleep 30
          
          # Проверяем статус всех контейнеров
          echo "Container status:"
          docker-compose ps
          
          # Проверяем логи проблемных сервисов
          echo "Backend logs:"
          docker-compose logs backend --tail=20
          
          echo "Client logs:"
          docker-compose logs client --tail=20
          
          echo "Voice server logs:"
          docker-compose logs voice-server --tail=20
          
          # Health check - проверяем HTTP сначала
          echo "Health check..."
          sleep 10
          
          # Проверяем что backend отвечает
          if curl -f http://localhost:8080 2>/dev/null || curl -f http://localhost:5109 2>/dev/null; then
            echo "Backend is responding!"
          else
            echo "Backend is not responding!"
            echo "Checking what ports are open:"
            netstat -tulpn | grep -E ':(8080|5109)'
            echo "Backend logs:"
            docker-compose logs backend --tail=10
            exit 1
          fi
          
          # Проверяем клиент
          if curl -f http://localhost:3001 2>/dev/null; then
            echo "Client health check passed!"
          else
            echo "Client health check failed!"
            docker-compose logs client
            exit 1
          fi
          
          # Проверяем голосовой сервер
          if curl -f http://localhost:3000 2>/dev/null; then
            echo "Voice server health check passed!"
          else
            echo "Voice server health check failed!"
            docker-compose logs voice-server
            exit 1
          fi
          
          echo "All services are healthy!"
          
          # Показываем статус контейнеров
          echo "Container status:"
          docker-compose ps

